[project]
name = "mplp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "m-beau", email = "maximebeaujeanroch047@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mplp = "mplp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
